### ISSUE TITLE
New Title Localization Still Buggy

### ISSUE THREAD

**Issue by AlexWyrmin** [Leviathonlx/CTPandNBCompatch#21]
Despite the corrections you made to the code, thank you by the way, the localization of the new titles is still buggy. Aside from re-adding in localization keys I had forgotten to upload in the first place, which I've already done on my end, I can't see where the problem might be. And until yesterday everything was fine too.

**Comment by AlexWyrmin** [comment]
Tackled the problem from another angle and apparently successfully solving it.

**Comment by Leviathonlx** [comment]
Which ones were still broke? I clicked around last night and didn't see any broken keys but I'll take a look at whichever ones aren't working.
